import numpy as np
import pandas
from sklearn.model_selection import StratifiedKFold
"""
Take as input CSV file of the feature vectors generated by DeepSpectrum.
Outputs 4 csv files by dividing data into 4 folds
"""

a = pandas.read_csv("/datasets/bip-all-ws_2-hs_1-mode_mel-net_AlexNet-l_fc6-cm_viridis.csv.csv", delimiter=',')
header_row = ','.join(a.columns)
a = a[a['class'] > 0] # drop kontrol sam
a = a.drop('name', 1)
idx = np.arange(a.shape[0])
labels = np.array(a['class'])

skf  =StratifiedKFold(n_splits=4, shuffle=False)
for i, (train, test) in enumerate(skf.split(idx, labels)):
  print("writing fold {}/4".format(i))
  x_tr = a.iloc[train]
  x_te = a.iloc[test]

  with open("/datasets/csvdata/fold.{}.tr.csv".format(i), "w") as ff:
#    ff.write(header_row)
    x_tr.to_csv(ff, mode="w", index=False)

  with open("/datasets/csvdata/fold.{}.te.csv".format(i), "w") as ff2:
#    ff2.write(header_row)
    x_te.to_csv(ff2, mode="w", index=False)

